University/Models/Professor.cs
using System.Collections.Generic;

namespace University.Models
{
  public class Professor
  {
    public int ProfessorId { get; set; }
    public string Name { get; set; }
    public string Gender { get; set; }
    public bool VaccinationStatus { get; set; }
    public virtual ICollection<CourseProfessor> JoinEntities { get; set; }
  }
}

University/Controllers/ProfessorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System;
using System.Linq;
using University.Models;

namespace University.Controllers
{
  public class ProfessorsController : Controller
  {
    private readonly UniversityContext _db;
    public ProfessorsController(UniversityContext db)
    {
      _db = db;
    }

    [HttpGet("/professors")]
    public ActionResult Index()
    {
      return View(_db.Professors.ToList());
    }

    [HttpGet("/professors/create")]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost("/professors/create")]
    public ActionResult Create(Professor professor)
    {
      _db.Professors.Add(professor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpGet("/professors/details/{id}")]
    public ActionResult Details(int id)
    {
      var thisProfessor = _db.Professors
        .Include(professor => professor.JoinEntities)
        .ThenInclude(join => join.Course)
        .FirstOrDefault(professor => professor.ProfessorId == id);
      return View(thisProfessor);
    }

    [HttpGet("/professors/edit/{id}")]
    public ActionResult Edit(int id)
    {
      var thisProfessor = _db.Professors.FirstOrDefault(professor => professor.ProfessorId == id);
      ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
      return View(thisProfessor);
    }

    [HttpPost("/professors/edit/{id}")]
    public ActionResult Edit(Professor professor)
    {
      _db.Entry(professor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpGet("/professors/delete/{id}")]
    public ActionResult Delete(int id)
    {
      var thisProfessor = _db.Professors.FirstOrDefault(professor => professor.ProfessorId == id);
      return View(thisProfessor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisProfessor = _db.Professors.First(professor => professor.ProfessorId ==id);
      _db.Professors.Remove(thisProfessor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

University/Views/Professors/Create.cshtml
@model University.Models.Professor;

<div class="container">
  <h3> Add Professor </h3>

  <div class="form-container d-flex flex-column">
    @using (Html.BeginForm())
    {
      <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, "text", new { @required = "required" })
      </div>
      <div class="form-group">
        @Html.LabelFor(model => model.Gender)
        @Html.TextBoxFor(model => model.Gender, "text", new { @required = "required" })
      </div>
      <div class="form-group">
        @Html.Label("Are you vaccinated?")
        @Html.RadioButtonFor(model => model.VaccinationStatus, "True", new { @id="vaccine_yes" })
        @Html.LabelFor(model => model.VaccinationStatus, "Yes")
        @Html.RadioButtonFor(model => model.VaccinationStatus, "False", new { @id="vaccine_no" })
        @Html.LabelFor(model => model.VaccinationStatus, "No")
      </div>

      <input type="submit" value="Add Professor" class="btn btn-block btn-primary">
    }
  </div>
</div>

University/Views/Professors/Delete.cshtml
@model University.Models.Professor

<div class="container">
  <h2>Are you sure you would like to delete this Professor?</h2>

  @Html.DisplayNameFor(model => model.Name) : @Html.DisplayFor(model => model.Name)

  @using (Html.BeginForm())
  {
    @Html.Hidden("id", @Model.ProfessorId)
    <input type="submit" value="Delete" class="btn btn-primary" />
  }
</div>

University/Views/Professors/Details.cshtml
@model University.Models.Professor;

<div class="container">
  <h2>Professor Details</h2>
  <h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
  <h3>@Html.DisplayNameFor(model => model.Gender): @Html.DisplayFor(model => model.Gender)</h3>
  <h3>@Html.DisplayNameFor(model => model.VaccinationStatus): @Html.DisplayFor(model => model.VaccinationStatus)</h3>

  @if(@Model.JoinEntities.Count == 0)
  {
    <p>This professor is not enrolled in any courses</p>
  }

  <h3>Registered Courses</h3>

  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <li>@join.Course.CourseName</li>
      @using (Html.BeginForm("DeleteCourse", "Professors"))
      {
        @Html.Hidden("joinId", @join.CourseProfessorId)
        <input type="submit" value="Delete"/>
      }
    }
  </ul>
    @Html.ActionLink("Remove Professor", "Delete", "Professors", new { id = Model.ProfessorId }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Edit Professor", "Edit", "Professors", new { id = Model.ProfessorId }, new { @class = "btn btn-primary" })
</div>

University/Views/Professors/Edit.cshtml
@model University.Models.Professor

<div class="container">
  <h2>Edit</h2>

  <h4>Edit this Professor: @Html.DisplayFor(model => model.Name)</h4>

  @using (Html.BeginForm("edit", "professors", new { @id = @Model.ProfessorId }, FormMethod.Post))
  {
    @Html.HiddenFor(model => model.ProfessorId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <div class="form-group">
      @Html.Label("Are you vaccinated?")
      @Html.RadioButtonFor(model => model.VaccinationStatus, "True", new { @id="vaccine_yes" })
      @Html.LabelFor(model => model.VaccinationStatus, "Yes")
      @Html.RadioButtonFor(model => model.VaccinationStatus, "False", new { @id="vaccine_no" })
      @Html.LabelFor(model => model.VaccinationStatus, "No")
    </div>

    @Html.Label("Courses")
    @Html.DropDownList("CourseId")

    <input type="submit" value="Save" class="btn btn-primary" />
  }

  <p>@Html.ActionLink("Home", "Index")</p>
</div>

University/Views/Professors/Index.cshtml
@using University.Models;

<div class="container">
  <div class="row">
    <h2 class="col-sm-8">Professors</h2>
    @Html.ActionLink("Add New Professor", "Create", "Professors", null, new { @class = "btn btn-primary col-sm-3" })
  </div>
  <div class="container content pt-5">
    @if (@Model.Count == 0)
    {
      <p>There are no Professors yet registered.</p>
    }
    else
    {
      <ul>
        @foreach (Professor professor in Model)
        {
          <li>
            @Html.ActionLink($"{professor.Name}", "Details", "Professors", new { id = professor.ProfessorId }, new { @class = "btn btn-primary" })
          </li>
        }
      </ul>
    }
  </div>
</div>